"""init 12 tables

Revision ID: 478d2b0819e6
Revises: 
Create Date: 2026-09-15 07:11:35.412625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d2b0819e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sekolah',
    sa.Column('npsn', sa.String(length=20), nullable=False),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.String(length=500), nullable=True),
    sa.Column('jenjang', sa.Enum('SD', 'SMP', 'SMA', 'SMK', name='jenjang'), nullable=False),
    sa.Column('status_sekolah', sa.Enum('Negeri', 'Swasta', name='status_sekolah'), nullable=True),
    sa.Column('kecamatan', sa.String(length=255), nullable=True),
    sa.Column('desa_kelurahan', sa.String(length=255), nullable=True),
    sa.Column('lintang', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('bujur', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('akreditasi', sa.String(length=5), nullable=True),
    sa.Column('nama_kepsek', sa.String(length=255), nullable=True),
    sa.Column('sumber_data', sa.String(length=50), nullable=True),
    sa.Column('tanggal_pembaruan_data', sa.Date(), nullable=True),
    sa.Column('tanggal_verifikasi_baseline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('npsn')
    )
    op.create_table('klaster',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('kategori', sa.Enum('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', name='kategori_klaster'), nullable=False),
    sa.Column('sekolah_npsn', sa.String(length=20), nullable=False),
    sa.Column('skor_keparahan', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('jumlah_vote_terhitung', sa.Integer(), nullable=False),
    sa.Column('skor_prioritas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('urutan_prioritas_override', sa.Integer(), nullable=True),
    sa.Column('alasan_override', sa.Text(), nullable=True),
    sa.Column('status_verifikasi', sa.Enum('menunggu_verifikasi', 'tidak_terverifikasi', 'terverifikasi', name='status_klaster'), nullable=False),
    sa.Column('status_penanganan', sa.Enum('dalam_antrian_prioritas', 'dalam_proses', 'selesai', 'tidak_dapat_ditindaklanjuti', name='status_penanganan'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sekolah_npsn'], ['sekolah.npsn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kondisi_sarana',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_npsn', sa.String(length=20), nullable=False),
    sa.Column('nama_ruang', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('kondisi_baik', sa.Integer(), nullable=False),
    sa.Column('kondisi_rusak_ringan', sa.Integer(), nullable=False),
    sa.Column('kondisi_rusak_sedang', sa.Integer(), nullable=False),
    sa.Column('kondisi_rusak_berat', sa.Integer(), nullable=False),
    sa.Column('sumber', sa.Enum('dapodik', 'laporan_warga', name='sumber_sarana'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sekolah_npsn'], ['sekolah.npsn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sekolah_npsn', 'nama_ruang', 'sumber', name='uq_sarana_per_jenis')
    )
    op.create_table('sekolah_data_resmi',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_npsn', sa.String(length=20), nullable=False),
    sa.Column('rasio_guru_siswa', sa.String(length=20), nullable=True),
    sa.Column('indikator_kualitas_data', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sekolah_npsn'], ['sekolah.npsn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('warga_umum', 'warga_terverifikasi', 'komite_sekolah', 'verifikator_dinas', 'kepala_dinas', 'admin', name='user_role'), nullable=False),
    sa.Column('status_verifikasi', sa.Enum('menunggu', 'terverifikasi', 'ditolak', name='status_verifikasi'), nullable=False),
    sa.Column('sekolah_terkait_npsn', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sekolah_terkait_npsn'], ['sekolah.npsn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aksi', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('diproses', 'selesai', 'gagal', name='ingest_status'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('baris_diproses', sa.Integer(), nullable=True),
    sa.Column('baris_gagal', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracking_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_npsn', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.Enum('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', name='kategori_laporan'), nullable=False),
    sa.Column('fasilitas_terkait', sa.String(length=255), nullable=True),
    sa.Column('kondisi_dilaporkan', sa.Enum('baik', 'rusak_ringan', 'rusak_sedang', 'rusak_berat', name='kondisi_dilaporkan'), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('klaster_id', sa.String(length=36), nullable=True),
    sa.Column('status_sanggahan', sa.Enum('menunggu', 'divalidasi', 'ditolak', name='status_sanggahan'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['klaster_id'], ['klaster.id'], ),
    sa.ForeignKeyConstraint(['sekolah_npsn'], ['sekolah.npsn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laporan_tracking_id'), 'laporan', ['tracking_id'], unique=True)
    op.create_table('pdp_vault',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nik_encrypted', sa.LargeBinary(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('status_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('klaster_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('menunggu_verifikasi', 'perlu_info_tambahan', 'tidak_terverifikasi', 'terverifikasi', 'dalam_antrian_prioritas', 'dalam_proses', 'selesai', 'tidak_dapat_ditindaklanjuti', name='status_log_status'), nullable=False),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['klaster_id'], ['klaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('klaster_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status_vote', sa.Enum('pending', 'terhitung', name='status_vote'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['klaster_id'], ['klaster.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('klaster_id', 'user_id', name='uq_vote_per_klaster_user')
    )
    op.create_table('laporan_foto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('laporan_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['laporan_id'], ['laporan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_foto')
    op.drop_table('vote')
    op.drop_table('status_log')
    op.drop_table('pdp_vault')
    op.drop_index(op.f('ix_laporan_tracking_id'), table_name='laporan')
    op.drop_table('laporan')
    op.drop_table('ingest_job')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sekolah_data_resmi')
    op.drop_table('kondisi_sarana')
    op.drop_table('klaster')
    op.drop_table('sekolah')
    # ### end Alembic commands ###
