"""F3: Update kategori_laporan enum to infrastruktur taxonomy

Revision ID: 8cca6e1b2fa3
Revises: 478d2b0819e6
Create Date: 2026-09-22 12:41:29.698599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8cca6e1b2fa3'
down_revision: Union[str, Sequence[str], None] = '478d2b0819e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data dummy laporan pakai kategori lama — hapus dulu agar ALTER ENUM tidak gagal.
    op.execute("DELETE FROM laporan_foto")
    op.execute("DELETE FROM vote")
    op.execute("DELETE FROM status_log")
    op.execute("DELETE FROM laporan")
    op.execute("DELETE FROM klaster")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('klaster', 'kategori',
               existing_type=mysql.ENUM('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ruang_belajar', 'sanitasi_air', 'utilitas', 'akses_lahan', 'penunjang', name='kategori_klaster'),
               existing_nullable=False)
    op.alter_column('laporan', 'kategori',
               existing_type=mysql.ENUM('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ruang_belajar', 'sanitasi_air', 'utilitas', 'akses_lahan', 'penunjang', name='kategori_laporan'),
               existing_nullable=False)
    op.alter_column('pdp_vault', 'nik_encrypted',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdp_vault', 'nik_encrypted',
               existing_type=sa.LargeBinary(length=255),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('laporan', 'kategori',
               existing_type=sa.Enum('ruang_belajar', 'sanitasi_air', 'utilitas', 'akses_lahan', 'penunjang', name='kategori_laporan'),
               type_=mysql.ENUM('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('klaster', 'kategori',
               existing_type=sa.Enum('ruang_belajar', 'sanitasi_air', 'utilitas', 'akses_lahan', 'penunjang', name='kategori_klaster'),
               type_=mysql.ENUM('infrastruktur_sarana', 'ketersediaan_tenaga_pengajar', 'lainnya', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
